#!/bin/sh
### BEGIN INIT INFO
# Provides:          node_exporter
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prometheus Node Exporter
# Description:       Starts Prometheus Node Exporter
### END INIT INFO

DAEMON=/usr/local/bin/node_exporter
DAEMON_NAME=node_exporter
DAEMON_OPTS=""
PIDFILE=/var/run/$DAEMON_NAME.pid
LOGFILE=/var/log/$DAEMON_NAME.log

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS >> $LOGFILE 2>&1
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    log_end_msg $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status_of_proc "$DAEMON" "$DAEMON_NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
